# base image: node-alpine latest LTS
# as build environment
FROM node:14.16.0-alpine as build

# set working directory
WORKDIR /app

# add `/app/node_modules/.bin` to $PATH
# this ensures that the executables created during the npm build process can be found 
ENV PATH /app/node_modules/.bin:$PATH

# install and cache app dependencies
# copying the JSON file rather than the whole working directory
# allows us to take advantage of Docker’s cache layers. 
COPY package.json /app/package.json
RUN npm install --silent
# RUN npm install @vue/cli@3.7.0 -g

# copy code to image and build app
COPY . /app
RUN npm run build



# base image: nginx alpine latest stable version
# as production environment
FROM nginx:1.18.0-alpine

# copy static site from build environment to production environment
COPY --from=build /app/dist /usr/share/nginx/html

# expose port and start nginx
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]